
\connect gtables;

INSERT INTO cuisines (name) VALUES ('American'), ('Italian'), ('Mexican'), ('Thai'), ('Vietnamese');

INSERT INTO restaurants (name, address_city, address_state, cuisine_id, rating, image_url, description)
VALUES ('McDonalds', 'Littleton', 'CO', 1, 5, 'burger.png', 'This extravagant restaurant caters the finest American cuisine for a fraction of the price of anywhere else! Hot mocha coffee to start the day. And a sausage biscuit. Friendly people here even if they aren''t the fastest at 6 AM.'),
('Pizza Hut', 'Dacono', 'CO', 2, 3, 'italian.png', 'This Pizza Hut is excellent! I haven''t had Pizza Hut in over a year but that has changed with the new menu. This Pizza Hut is consistent in quality and has nice employees. Keep up the great work! You guys are awesome.'),
('Taco Bell', 'Denver', 'CO', 3, 5, 'mexican.png', 'I moved to Colorado in 2009 from California and have been on the search for great Mexican food. I think I finally found it! I ordered the carne asada taco and chorizo with eggs plate. The carne asada taco was generously filled with steak and topped off with pico de gallo and Guacamole (could have done without the guacamole). Excellent! The chorizo with eggs plate was amazing. Big portions and great flavor. The flour tortilla they give with the plate is huge and tastes homemade. Finally found a place that makes their rice and beans taste like my favorite California Mexican food joints.  Highly recommend.'),
('Phò99', 'Denver', 'CO', 5, 2, 'pho.jpg', 'The broth is so soothing. The herbs are awesome great for what ails you. The number 7 is the best. I put everything in. It''s so good with the basil and sprouts, the jalepeno is the best fresh spice heat is perfect. Enough for 2 meals with large #7.'),
('Thai Kitchen', 'Portland', 'OR', 4, 4, 'thai.jpg', 'Very good chicken pad Thai. I ordered hot and the spice level was perfect! Hot with a kick but not overwhelming. The rest of the flavor profile was great as well. Having spent a considerable amount of time in Thailand I am somewhat of a expert on Pad Thai. It was quite good. Had a brief conversation with the owner and he was quite pleasant.'),
('Maggianos', 'Centennial', 'CO', 2, 5, 'italian.png', 'My girlfriend and I regularly go here for special occasions since it is where we had our first date and it has never failed to impress me. Awesome staff, food is ready quickly and is always wonderful in taste and appearance! I recommend the Marco''s Meal for Two for date nights- its a killer deal for a ton of food for a great price. Note: You WILL be stuffed afterwards!');